### ISSUE TITLE
Quotes in css string breaks

### ISSUE THREAD

**Issue by boopathi** [boopathi/react-svg-loader#1]
example:

`styles="font-family: \"Roboto Light\""` would break. stylesAttr parser requires rewrite. 

Another question would be, do you see quoted values in css in svg files ?

**Comment by MoOx** [comment]
I don't really care about the svg content (since I don't handle them I call a designer or I create them using illustrator/sketch).

**Comment by boopathi** [comment]
Rewrite #12 - and https://github.com/boopathi/react-svg-loader/commit/63ec84fb7d742b9c972750ef2feb9bf3b59f72b4 fixes this .. It will escape the quotes and preserve it.
