### ISSUE TITLE
First attribute is being skipped.

### ISSUE THREAD

**Issue by munsu** [boopathi/react-svg-loader#10]
This is being rendered correctly:
`<svg xmlns="http://www.w3.org/2000/svg" height="16" width="14">
  <path d="..." />
</svg>`
This somehow loses its height attribute:
`<svg height="16" width="14" xmlns="http://www.w3.org/2000/svg">
  <path d="..." />
</svg>`

Found this bug while trying out the svg's here: https://github.com/github/octicons/tree/master/svg

**Comment by boopathi** [comment]
I fixed the issue with this. Feel free to open this again if this is still doesn't work for you.
