### ISSUE TITLE
Suggestion: Leave SVGO out of this package

### ISSUE THREAD

**Issue by romulof** [boopathi/react-svg-loader#140]
You can easily add SVGO to the pipeline on Webpack, so leave it out of your package to reduce complexity.

Webpack 2 example:
```js
{
  test: /\.svg$/,
  loaders: [
    'babel-loader',
    'react-svg-loader',
    {
      loader: 'svgo-loader',
      options: {
        floatPrecision: 2
        plugins: [{removeTitle: false}],
      }
    },
  ]
}
```

**Comment by boopathi** [comment]
SVGO is used to remove doctype and comments and get an SVG which can also act as a valid JSX.

**Comment by romulof** [comment]
Wouldn't be better to use a XML parser for these things?

**Comment by boopathi** [comment]
Then we have to transform XML AST to JavaScript AST to get JS output, while JSX is JavaScript + some HTML and can be solved with one parser (babylon, babel) - solves for common use cases.

**Comment by romulof** [comment]
How about this:
1) Convert to XML AST
2) Manipulate structure: remove comments, attributes, convert from dash to camel case, etc
3) Render to String
4) Continue with your current parser

**Comment by boopathi** [comment]
`1`, `2`(remove comments and doctype) and also fix up invalid XML and `3` - is exactly what SVGO already does. Since we already use SVGO, it'd be good and easy just to expose the API.

**Comment by romulof** [comment]
Ok, you made your point 👍

**Comment by pluma** [comment]
Just an FYI: I've had react-svg-loader blow up because an SVG contained CSS (which contains curly braces which JSX treats specially) so this approach is pretty error prone.

**Comment by romulof** [comment]
Makes sense, @pluma.
Thanks for sharing!

**Comment by boopathi** [comment]
@pluma #38
