### ISSUE TITLE
Unable to convert to react component 

### ISSUE THREAD

**Issue by kamarajuPrathi** [boopathi/react-svg-loader#143]
React Component
```
import React from 'react'
import CupImage from './cup.svg'
class DashBoard extends React.Component{
render(){
return <div><CupImage/></div>
}
}
export default DashBoard

```
WebpackConfig.js
{
  test: /\.svg$/,
  loaders: [
    {
      loader: 'babel-loader',
      query: {
        presets: ['es2015']
      }
    },
    {
      loader: 'react-svg',
      query: {
        jsx: true
      }
    }
  ]
}

Please let me know if i am missing some thing here in above example .

Unable to load this image having this below issue
TypeError: Cannot call a class as a function

**Comment by boopathi** [comment]
What version of webpack are you using?

**Comment by kamarajuPrathi** [comment]
2.2.1

**Comment by kamarajuPrathi** [comment]
@boopathi  any update ?

**Comment by souporserious** [comment]
Getting the same `TypeError: Cannot call a class as a function` as well 😕

**Comment by boopathi** [comment]
Can you create a repo with minimal code that reproduces this bug ?

**Comment by kubens** [comment]
Hmm if you using webpack2 try use this:

```
      {
        test: /\.svg$/,
        use: [
          'babel-loader',
          'react-svg-loader?' + JSON.stringify({
            svgo: {
              plugins: [{removeTitle: false}],
              floatPrecision: 2
            }
          })
        ]
      }
```

**Comment by abhishek9** [comment]
@souporserious  , @kamarajuPrathi : Have you got a solution to your problem? I am facing same issue at my end.

**Comment by boopathi** [comment]
@kubens With webpack2, you can pass options like this - https://github.com/boopathi/react-svg-loader#webpack-2x . You don't need `JSON.stringify`.

**Comment by boopathi** [comment]
webpack<2 support is dropped in master.
