### ISSUE TITLE
Support for SVG in CSS files

### ISSUE THREAD

**Issue by volkanunsal** [boopathi/react-svg-loader#149]
This is a great loader, but it shouldn't break when the svg file is loaded by an scss file. As in this example:

```scss
.foo {
   background-image: url(images/icon.svg);
}
```

Currently, these images are loaded as `[object Object]` strings.

**Comment by boopathi** [comment]
I faced the same with image-size-loader and I solved it with a small [hack](https://github.com/boopathi/image-size-loader/blob/a103419df319eb8ad79bc5f97ce63e30203e187e/index.js#L14-L19)

Would appreciate a PR if the same hack works for this.

**Comment by andersaloof** [comment]
Could also be fixed by separating SVG files used in JS and CSS into two different folders, and adjust the webpack config to only use react-svg-loader on SVG files in one of the folders...

```
test: /.svg-js(.*)\.svg$/,
```

**Comment by amazingandyyy** [comment]
@andersaloof  can you show more code about this implement? Then how can I only use `file-laoder`
for svg in scss, I tried `/.svg-scss(.*)\.svg$/` but it doesn't work out.

Please help me out. I already spent over three days struggling with using svg in both jsx and scss

**Comment by MartinDawson** [comment]
Why was this not fixed in 2.0.0... It's a huge issue.

**Comment by davepenfold** [comment]
This issued can be solved by using Webpacks `Rule.oneOf` and `resourceQuery`: https://webpack.js.org/configuration/module/#rule-oneof

By using this option in your webpack config, you can use `react-svg-loader` for JSX files, and another loader, say `url-loader`, in your CSS, Sass etc... files.

**Comment by P0lip** [comment]
There is a very clean way to achieve it.
Just use the `issuer` field, which should be equal to file that initiated the import.
```
// In your webpack config
{
  test: /\.svg$/,
  issuer: /\.jsx?$/,
  use: [
    {
      loader: "babel-loader"
    },
    {
      loader: "react-svg-loader",
 
      options: {
        jsx: true // true outputs JSX tags
      }
    }
  ]
}
```
If you have any other loaders (like file-loader etc.) matching `/\.svg$/` pattern, you may need to apply that rule for them as well, i.e. `issuer: /\.s?css$/,`

**Comment by MartinDawson** [comment]
@P0lip I tried this.

I get: 

```
ERROR in ./wwwroot/assets/arrow-down.svg
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
```

css:

```css
  .howItWorksItem:after {
    content: '';
    background: url(../../wwwroot/assets/arrow-down.svg);
  }
```

Is `issuer` only available in webpack 4?
