### ISSUE TITLE
Update Readme, Removed unused dependencies

### ISSUE THREAD

**Issue by palamccc** [boopathi/react-svg-loader#150]
> By default the loader outputs ES2015 code (with JSX compiled to JavaScript using babel-preset-react). You can combine it with babel-loader to compile it down to ES5.

Loader converts svg to jsx file, but Readme claims that svg is converted to es2015 code. please update readme and remove 'babel-preset-react' dependency.

I can also send pull request, if you are open to it.

**Comment by palamccc** [comment]
I was wrong, i found 'babel-preset-react' used here.  https://github.com/boopathi/react-svg-loader/blob/653045008d89e7bc7835872b620e3cbbdb264221/src/loader.js#L29

My request is, just generate jsx code, and leave other transformations to others loaders in webpack.
Just like [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)

**Comment by boopathi** [comment]
Yeah. I want to remove es2015 preset as well in favour of preset-env. I'd welcome a PR 😃

**Comment by boopathi** [comment]
Done. babel-preset-es2015 is removed.
