### ISSUE TITLE
Compatibility with Rollup

### ISSUE THREAD

**Issue by osdiab** [boopathi/react-svg-loader#159]
It would be super cool if it were possible to use this plugin with Rollup. At my company we're working on a React components library, wherein we don't want webpack's bundling, but we do want our svg files to be requirable as React components. I'll investigate what it would take to do this.

**Comment by osdiab** [comment]
this may be best as a fork, as this repository seems to be pretty focused as a webpack loader. Are there examples of repositories that are both webpack loaders and rollup plugins?

**Comment by boopathi** [comment]
From what I understand, Rollup mainly focuses on JavaScript with ESModules. webpack on the other hand handles all types of files. You can still use the react-svg-loader CLI to generate the relevant javascript files and use these generated files in Rollup.

**Comment by osdiab** [comment]
Rollup can handle all files in the same way as Webpack, as evident in [the list of plugins](https://github.com/rollup/rollup/wiki/Plugins) for that bundler. Rollup as a build tool is more intended [for libraries](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c), because you can export to ES6 modules, enabling consumers using build tools like Rollup and Webpack 2 to tree shake it. Unfortunately, [Webpack does not support that functionality yet](https://github.com/webpack/webpack/issues/2933) (although hopefully it will soon!).

My use case is that my company has a components library that includes some assets like inlined SVGs. I could just convert them all to React components, although I would prefer if I could just use a loader to convert them at compile time so that they can remain transparently in SVG format, and so future SVGs can be added with little effort. I'll look into the feasibility of this in my own fork.

**Comment by osdiab** [comment]
Looks like someone's implemented it but it's in progress: https://github.com/pegjs/pegjs/pull/481

**Comment by boopathi** [comment]
[rollup-plugin-react-svg](https://github.com/boopathi/react-svg-loader/tree/master/packages/rollup-plugin-react-svg) is available from 2.1.0
