### ISSUE TITLE
Publishing new versions and getting off Alpha

### ISSUE THREAD

**Issue by dylang** [boopathi/react-svg-loader#161]
Hi, I hate to be a bother as I can see you are already spread thin over many worth-while open source projects. 

I was wondering what's required before a new version (alpha.2?) can be published with the webpack deprecations fixes (#147), and what you are hoping for to transition from `alpha` to a regular semver release. 

Thanks!

**Comment by hankthewhale** [comment]
@boopathi any info here?

**Comment by enisdenjo** [comment]
@boopathi same question here 😄

**Comment by boopathi** [comment]
Thanks. I made a few breaking changes I had in my todo list. Will publish it soon. No estimates yet!
