### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by kimamula** [boopathi/react-svg-loader#164]
I was surprised to see how many packages are installed along with react-svg-loader when I execute `npm install react-svg-loader`.

What about extracting core functionality of react-svg-loader and publishing it as another package that does not depend on cli or babel related packages?

**Comment by boopathi** [comment]
https://github.com/boopathi/react-svg-loader#internals would explain the role of each dependency.

Also check #140 and #38 for related discussion on why some dependencies are required. 

I'm going to close this now. If there is something that can be removed, please send a PR.

**Comment by OZZlE** [comment]
It's 400 KB minified+gzipped though.. It seems like around half is babel stuff that will probably be used anyway and brough up as a top level requirement by node but 200 KB is still a lot!

Just wished React offered to compile stuff like this before-hand! Doesn't make sense that every client should download 200 KB and parsing to show a simple SVG..
