### ISSUE TITLE
Unexpected token: name (SVG)

### ISSUE THREAD

**Issue by halt-hammerzeit** [boopathi/react-svg-loader#169]
`2.0.0-alpha.1`

My webpack loader config is the default one

```js
{
    test: /\.(svg)$/,
    use: [{
      loader: 'react-svg-loader'
    }]
  }
```

Which outputs

```js
class SVG extends __WEBPACK_IMPORTED_MODULE_0_react___default.a.Component {
  render() {
    return __WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement(
      "svg",
```

And the error is:

```
[19:53:28] Error: Fix the following webpack build errors:

main.2de7c4a952203664e4cf.js from UglifyJs
Unexpected token: name (SVG)
```

So it doesn't compile `class` to ES5 syntax.
What is the Webpack loader config for the default behaviour with ES5 transpilation?
Perhaps it would make sense to make it the default behaviour since no one would use `class`es in their JS currently.

**Comment by boopathi** [comment]
You should use babel-loader to transpile to es5

An example with webpack 2 and above is here - https://github.com/boopathi/react-svg-loader#webpack-2x ..

**Comment by halt-hammerzeit** [comment]
This is still not resolved.
And this is still not a "question" and is a bug instead.
Not to mention that it should transpile to ES5 by default without adding any additional options, it throws yet another error.

```js
./assets/images/close.svg
Module build failed: SyntaxError: Unexpected token (4:11)

  2 | export default class SVG extends React.Component {
  3 |   render() {
> 4 |     return <svg viewBox="0 0 22 21" xmlns="http://www.w3.org/2000/svg" {...this.props}><title>0ECB348C-8E50-4195-AB44-FDEF7D1C0481</title><g stroke="#555A5E" strokeWidth="2" fill="none" fillRule="evenodd" strokeLinecap="round"><path d="M1.808 1.308l18.384 18.384M20.192 1.308L1.808 19.692" /></g></svg>;
    |            ^
  5 |   }
  6 | 
  7 | }

Error
    at transpile (/Users/kuchumovn/work/JITUApp/node_modules/babel-loader/lib/index.js:61:13)
    at Object.module.exports (/Users/kuchumovn/work/JITUApp/node_modules/babel-loader/lib/index.js:163:20)
```

For non-default Webpack loader configuration

```js
{
    test: /\.(svg)$/,
    use: [{
      loader: 'babel-loader'
    }, {
      loader: 'react-svg-loader'
    }]
  }
```

I'm migrating back to `svg-react-loader`.

**Comment by halt-hammerzeit** [comment]
Oh, I got it now, it seems to work – the latest `2.0.0-alpha.1` version has to be used, not `@latest` which is `1.x`.
Ok, this is still more verbose than `svg-react-loader` and also `svg-react-loader` handles `<style/>` tags (and this library gave me errors so I migrated `<style/>` tags inside SVG to inline styles by hand).
This issue is resolved then.

**Comment by nihiluis** [comment]
900% agree was very confused as well

**Comment by fernandofleury** [comment]
I ended up changed to another loader as well.

**Comment by saiumesh-letznav** [comment]
> Oh, I got it now, it seems to work – the latest `2.0.0-alpha.1` version has to be used, not `@latest` which is `1.x`.
> And the correct Webpack config is:
> 
> ```js
> {
>     test: /\.svg$/,
>     use: [{
>       loader: 'babel-loader'
>     }, {
>       loader: 'react-svg-loader'
>     }]
>   }
> ```
> 
> This is still more verbose than `svg-react-loader` and also `svg-react-loader` handles `<style/>` tags and CSS classes (and this library gave me errors so I migrated `<style/>` tags inside SVG to inline styles by hand).
> But at the same time the author of `svg-react-loader` doesn't communicate at all in the issues and PRs.
> This issue is resolved then.
> 
> **UPDATE**
> Migrating back to `react-svg-loader` because `svg-react-loader` has a filename bug
> [jhamlet/svg-react-loader#72](https://github.com/jhamlet/svg-react-loader/issues/72)

Thanks!! I was able to solve issue.
