### ISSUE TITLE
Conversion removes width attribute 

### ISSUE THREAD

**Issue by SpadarShut** [boopathi/react-svg-loader#17]
I am transforming some SVG files, all them have only viewBox, width and height attributes, but after running react-svg-loader (via CLI) the width attribute is missing in the component. Is it necessary to run it wth some special parameters?

**Comment by boopathi** [comment]
Can you give me an example ?

**Comment by SpadarShut** [comment]
@boopathi 
This is an example file:
`<svg width="24" height="24" viewBox="0 0 24 24"><path d="M7,10 L17,10 L12,15 L7,10 Z"/></svg>
`
This is the final output:

`
import React from 'react';
export default class extends React.Component {
  render() {
    return <svg { ...this.props } height={'undefined' === typeof this.props['height'] ? "24" : this.props['height']} viewBox={'undefined' === typeof this.props['viewBox'] ? "0 0 24 24" : this.props['viewBox']}>
  <path d="M7,10 L17,10 L12,15 L7,10 Z"/>
</svg>;
  }
}
`

**Comment by boopathi** [comment]
Yes. It's the expected behaviour. It allows you to propagate props from the React component to svg.

So you can use it like,

```js
const MyImage = require('./svg');
<MyImage width="50"/>
// height and viewBox will be the default already set in SVG. 
```

**Comment by SpadarShut** [comment]
But why height is present and width is not? How can I keep both?

**Comment by boopathi** [comment]
I don't know what you mean, but I just gave a name to the component generated and here is a demo of the same - 

http://jsbin.com/marijeqasu/3/edit?js,console,output

The width and height are default in the second component

In the first, the width from props overwrite the one that's default.

**Comment by SpadarShut** [comment]
@boopathi I run `'npm bin'/svg2react *.svg` in command line to generate js conponents from .svg files. 
In the output *.svg.react.js files there are checks for height and viewBox attributes (like `height={'undefined' ...}`), but no such thing for the width attribute, even though it is present in the source file. So I'm asking how can I keep it in the output .svg.react.js file, so that I don't need to write the width attribute when I'm using this icon component in the app.

**Comment by boopathi** [comment]
Ah!. Okay.

I'm not sure why width attribute is missing. Will check.

Are you using 0.1.0 version ? Would you mind upgrading to 1.0.0 ?. Lots of internal changes went in, but it's generates the same out.

**Comment by SpadarShut** [comment]
Upgrading to 1.0 fixes the issue. Many thanks!
