### ISSUE TITLE
ARIA Accessibility elements through props

### ISSUE THREAD

**Issue by petermikitsh** [boopathi/react-svg-loader#171]
It would be nice if I could do this:

```jsx
import MySvg from './MySvg.svg';

function renderWithAccessibility() {
  return <MySvg title="title" desc="desc"/>;
}
```

and the SVG was transformed to this:

```svg
<svg>
  <title>title</title>
  <desc>desc</desc>
</svg>
```

To support [ARIA SVG accessibility](https://www.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/).

Thoughts from package maintainers?

**Comment by boopathi** [comment]
Yes. Sure. PR Welcome 👍
