### ISSUE TITLE
Why not stateless functional component?

### ISSUE THREAD

**Issue by dalgard** [boopathi/react-svg-loader#173]
Why export a class that extends from React.Component instead of a stateless functional component?

The SVG component doesn't have state or any other advanced properties.

```jsx
import React from "react";

export default (props) => <svg {...props}>...</svg>;
```

https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc

**Comment by boopathi** [comment]
Done. (in master now)
