### ISSUE TITLE
Support filename as displayName ?

### ISSUE THREAD

**Issue by jfeldstein** [boopathi/react-svg-loader#174]
Eg:

```
import Logo from 'images/our_company_logo.svg';

// <Logo /> outputs <SVG />
```
It'd be great to have:
```
import Logo from 'images/our_company_logo.svg';

// <Logo /> outputs <OurCompanyLogo />
```

As far as I can tell it'd involve changing line 114 here https://github.com/boopathi/react-svg-loader/blob/34c99e4ecbf9284d0539880699bc44e4ec5a5d15/src/plugin.js#L114  to take advantage of the optional second argument of [`getExport`](https://github.com/boopathi/react-svg-loader/blob/34c99e4ecbf9284d0539880699bc44e4ec5a5d15/src/plugin.js#L58), in order for the displayName of the resulting component to equal the camelcase'd equivalent of the filename of the file being transpiled. 

You can see that the className attribute is, by default, "SVG". Since no name is provided, whenever we use the components transpiled by this loader, they always appear in the debugger and in enzyme tests as "<SVG />". We want them to instead appear as the name of the file. 

That's about as close as I can get on my own. I'm unclear how to make this change. 

Any suggestions? Happy to look into it more if someone can provide a little guidance!

**Comment by boopathi** [comment]
I have now converted it to an ArrowFunction(master branch) instead of React Component Class. So this isn't required. If there is a lot of interest in the name of the Component, comment here. For now I'll close this one.

**Comment by burrack** [comment]
I would like to change the component Name by passing displayName as attribute or any other easy way that will make it easy to change the component name.

Right now, this is what i see:
![image](https://user-images.githubusercontent.com/25310016/37880901-87bc34a6-305d-11e8-9cfe-52a066aa28fc.png)

**Comment by rouberg** [comment]
I'd like to have a better displayName automatically rather than `__WEBPACK_DEFAULT_EXPORT__`, or just expose an API to set it.
