### ISSUE TITLE
How to use in unit testing mocha?

### ISSUE THREAD

**Issue by MartinDawson** [boopathi/react-svg-loader#176]
Example:

```
import Spinner from '../../../../images/spinners/ellipsis.svg';

const Spinner = () => (
    <Spinner {...props} />
);
```

```
describe('SpinnerButton', () => {
  it('should render spinner svg', () => {
    const wrapper = shallow(<Spinner />);

    expect(wrapper.find('Spinner').length).toBe(1);
  });
});
```

webpack.config.js:
```
{
        test: /\.svg$/,
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'react-svg-loader',
            options: {
              svgo: {
                plugins: [{ removeTitle: false }],
                floatPrecision: 2,
              },
            },
          },
        ],
      },
```

This test will fail. It can't seem to find the Spinner. How do I fix this?

**Comment by boopathi** [comment]
Marking it as inactive. Please comment to reopen if you still have issues.

**Comment by icirellik** [comment]
I have the same issue. Was there a reason this was closed without a resolution?

**Comment by cjbuchmann-work** [comment]
I'm having the same issue here as well, and was hoping that I could some instruction on integrating this into our testing environment. In our Jest suite, it seems like this doesn't get loaded properly.

I was originally using this without the webpack configuraiton and doing

```javascript
const icon = require(`react-svg-loader!./icons/${ name }.svg`);
```

This worked fine outside of testing, but in testing it threw a `Cannot find module` error on an icon with a valid path.

I tried integrating the webpack configuration and my require then switched to

```javascript
const icon = require(`./icons/${ name }.svg`);
```

Which also works fine outside of testing. During testing it throws the error

```bash
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<?xml version="1.0" encoding="UTF-8"?>
                                                                                             ^
    
    SyntaxError: Unexpected token <
```

So it doesn't seem like the react-svg-loader is being properly integrated, but I can't see why. Any help here would be appreciated.
