### ISSUE TITLE
Switch to `import * as React` syntax?

### ISSUE THREAD

**Issue by coreh** [boopathi/react-svg-loader#179]
Right now this module uses the following syntax for the react import on the generated code:

```javascript
import React from 'react';
```

That works fine when transpiling code under babel (since babel includes a helper function that maps `module.exports` on CommonJS modules to the `default` ES6 export) but fails when using  TypeScript as a transpiler.

I'd like to propose switching to the following syntax (or adding an option to do so) to ensure compatibility with TypeScript:

```javascript
import * as React from 'react';
```

Thanks in advance!

**Edit:** I've patched it in my fork, if you'd like I can open a pull request, it's a one line change:

### src/plugin.js

```diff
@@ -121,7 +121,7 @@ export default function (babel) {
       path.node.body.unshift(
         t.importDeclaration(
           [
-            t.importDefaultSpecifier(t.identifier('React'))
+            t.importNamespaceSpecifier(t.identifier('React'))
           ],
           t.stringLiteral('react')
         )
```

**Comment by neoziro** [comment]
@coreh you should take a look at [svgr](https://github.com/smooth-code/svgr).
