### ISSUE TITLE
console errors parsing metadata tags

### ISSUE THREAD

**Issue by femans** [boopathi/react-svg-loader#181]
Hi, 
awesome loader!
I get several console errors after parsing the following piece of svg:
```
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg932"
   version="1.1"
   viewBox="0 0 79.374998 79.375002"
   height="300"
   width="300">
  <defs
     id="defs926" />
  <metadata
     id="metadata929">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
...
```
namely: 
`proxyConsole.js:56 Warning: Unknown props `xmlnsDc`, `xmlnsCc`, `xmlnsRdf`, `xmlnsSvg` on <svg> tag. Remove these props from the element.`

`proxyConsole.js:56 Warning: Unknown prop `rdfAbout` on <cc:Work> tag. Remove this prop from the element.`

`proxyConsole.js:56 Warning: Unknown prop `rdfResource` on <dc:type> tag. Remove this prop from the element. `

**Comment by boopathi** [comment]
Can you add the stack trace. I'm not sure where the `proxyConsole.js` comes from.
