### ISSUE TITLE
Published version on npm is outdated?

### ISSUE THREAD

**Issue by kmck** [boopathi/react-svg-loader#182]
Hi there! `1.1.1` on npm is pretty outdated now, and `2.0.0-alpha.1` seems like it is not up-to-date with this repo. Anything preventing publishing of `2.0.0`? If so, happy to help out in any way I can.

**Comment by boopathi** [comment]
Hi, thanks. I've made a couple of changes and published alpha. Hoping to publish the next few versions soon. Any bug reports / pull requests welcome.

**Comment by are1000** [comment]
Is there any way to use `2.0.0`? I tried to install from npm specifying version `react-svg-loader@2.0.0-alpha` (and various other combinations) - npm couldn't find the version. I also tried to install from git but it failed every time with `ENOENT: no such file or directory, chmod 'C:\cygwin64\home\ArturW\BeaconLocationAnalyzerClient\node_modules\react-svg-loader\lib\cli.js'`.

**Comment by boopathi** [comment]
It's published with tag `alpha` ... `npm install react-svg-loader@alpha`
