### ISSUE TITLE
Update to SVGO v1.0.0

### ISSUE THREAD

**Issue by marcofugaro** [boopathi/react-svg-loader#192]
SVGO just got updated! It has some really nice features, such as the `inlineStyles` plugin.

https://github.com/svg/svgo/releases

**Comment by qur2** [comment]
Or `addAttributesToSVGElement` with support for values.

**Comment by eigood** [comment]
As a quick test, I did `rm -rf node_modules/react-svg-core/node_modules/svgo`, to see if this package would just work transparently with a newer svgo version; it doesn't, it deadlocks.  Most likely due to some uncaught exception not calling a Promise.reject() someplace.

**Comment by eigood** [comment]
I've got this working now locally, I'll get a MR up shortly.

**Comment by marcofugaro** [comment]
So is this issue solved?

**Comment by butchler** [comment]
I'd like to use this loader, but the lack of the `inlineStyles` plugin is blocking me from being able to use it (since the SVGs I'd like to convert have `<style>` tags which get removed, losing the `fill`/`stroke` values).

Any idea when this fix will be published to NPM?

**Comment by augbog** [comment]
It does sound like this issue can be closed now. The style element has its own issue now.

**Comment by kinetifex** [comment]
I am running into the `<styles>` issues as well. I seems `svgo` was upgraded in the core package, but has not be published yet. Can we get a new release cut please with these fixes?
