### ISSUE TITLE
Error: <svg> attribute height: Expected length, "auto".

### ISSUE THREAD

**Issue by jadidian** [boopathi/react-svg-loader#194]
![screen shot 2017-11-18 at 1 12 24 am](https://user-images.githubusercontent.com/650099/32970416-1fe77cb4-cbfe-11e7-8aac-78871a03c064.png)

I get this console error `Error: <svg> attribute height: Expected length, "auto".` in Chrome, despite I've set the height to `auto`, in my code:
```js
import SomeSVG from 'assets/icons/some-icon.svg';
.
.
<SomeSVG className={ classes.icon } viewBox="0 0 64 64" width="100%" height="auto" />
```
and when I inspect the HTML element, the height is `auto`,
```html
<svg baseProfile="full" xmlns="http://www.w3.org/2000/svg" height="auto" width="100%" class="Icon-icon-2559" viewBox="0 0 64 64">...</svg>
```
not really sure where these errors come from, maybe the height is set to `auto` after these errors are thrown, or am I missing something?

I'm using `react` and `react-dom` 15.6.1, a project based on [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)

P.S. thanks for the awesome library.

**Comment by penhlenh** [comment]
You can set `height='100%'` which will render the same as auto.

**Comment by jadidian** [comment]
totally forgot about this issue, @penhlenh thanks for your reply, however I could get rid of the error messages by using styles `{ width: '100%', height: 'auto' }` instead of setting inline width and height.

**Comment by sohailupu** [comment]
i am still facing same issue after proper style setups

**Comment by naimlatifi5** [comment]
> You can set `height='100%'` which will render the same as auto.

Not in all browsers though. I had the same issue with width where Safari doesn't understand width/height in percentage which makes the SVG icon behave incorrectly just for Safari :)
