### ISSUE TITLE
Incorporate svgo optimizations into babel plugin

### ISSUE THREAD

**Issue by Andarist** [boopathi/react-svg-loader#198]
Is there any particular reason why the optimization happens in rollup plugin / webpack loader and not while transforming the input file with babel?

**Comment by boopathi** [comment]
The SVGO optimizations happen in those places (webpack loader, rollup plugin - which uses babel plugin) so that babel-parsing SVG as JSX works. Related discussion - https://github.com/boopathi/react-svg-loader/issues/140

**Comment by Andarist** [comment]
> The SVGO optimizations happen in those places (webpack loader, rollup plugin - which uses babel plugin)

Yeah, that I know. I'm more concerned about pure babel plugin though. Does `svgo` produce output that is not parseable as jsx?

**Comment by boopathi** [comment]
I don't think it's possible to add svgo as a part of babel plugin - i.e. to transform before the parsing takes place. SVGO with (remove doctype, remove comments, remove style tags) is valid JSX (though not aware of other corner cases if they exist).

But if your SVG is already valid JSX, then you can simply include another plugin - something like - 

```js
module.exports = ({ template }) => ({
  visitor: {
    Program(path) {
      path.replaceWith( 
        template(
          svgo.optimize(
            path.getSource()
          )
        )()
      )
    }
  }
})
```

and use it alongside `babel-plugin-react-svg` that converts other elements

**Comment by Andarist** [comment]
Wouldnt it be nice to have this under the flag in the core plugin? I understand that not all SVGs (when they are not valid JSX) could benefit from it, but it would still allow some optimizations without need to alter the source file.

If you feel this should be a part of my custom workflow though, feel free to close the issue.

**Comment by boopathi** [comment]
I want to solve for both cases -

1. SVGs parsed & transformed via SVGO so it could be valid JSX
2. SVGs which are already valid JSX

`react-svg-core` contains svgo transformations and runs `svgo -> babel transform`. 

Now if babel-plugin is supposed to include svgo plugin (let's say under an option), now - 

+ svgo will be dependency of both babel-plugin as well as `react-svg-core`. This seems unnecessary
+ It becomes easy to have a setup where svgo runs twice - once as a part of babel-plugin and once as a part of react-svg-core. This should be avoidable.

I'm open to other ideas.

**Comment by Andarist** [comment]
> svgo will be dependency of both babel-plugin as well as react-svg-core. This seems unnecessary

`svgo` can be made an `optionalDependency` of babel plugin, but overally this shouldnt be a problem - if you keep in sync svgo versions (if chosing the `optionalDependency` route i'd say it should be specified as `MAJOR.x`) they will be deduped across webpack loader and babel plugin

> It becomes easy to have a setup where svgo runs twice - once as a part of babel-plugin and once as a part of react-svg-core. This should be avoidable.

Using `svgo` in babel transform should be an opt-in, running twice `svgo` in case of bad configuration also shouldn't be much of a problem (it won't make svg unusable). Don't know how we could guard people against configuring this in a wrong way..

**Comment by Andarist** [comment]
@boopathi this could possibly be solved somewhat better (regarding range of SVGO optimizations) with introducing optional "inline" mode, just like in [babel-plugin-inline-react-svg](https://github.com/kesne/babel-plugin-inline-react-svg#babel-plugin-inline-react-svg). That way we could load the svg source file on our own, apply svgo and transform then with the regular transform. WDYT? Ofc I'm willing to implement this.

**Comment by boopathi** [comment]
I imagine it to look like this - 

+ SVGO could be a peer dependency for babel-plugin
+ Babel plugin takes an option `{ svgo = false /*default false*/ }` which runs the program node via svgo before applying other transforms ?

yeah?

> I'm willing to implement this.

Sure. Thanks.

**Comment by edahlseng** [comment]
Have there been any updates on this?
