### ISSUE TITLE
How do I pass my custom svgo plugin to the --svgo

### ISSUE THREAD

**Issue by SpadarShut** [boopathi/react-svg-loader#20]
Is it possible to run my own SVGO plugin and how do I pass it as an option if it is?

**Comment by boopathi** [comment]
I don't know. How would you pass custom plugins to SVGO anyway ?

https://github.com/svg/svgo#how-to-use - I don't see custom plugins.

**Comment by SpadarShut** [comment]
You are right, this should be an svgo issue actually.
