### ISSUE TITLE
Remove Style Element is an essential SVGO Plugin

### ISSUE THREAD

**Issue by Oromis** [boopathi/react-svg-loader#200]
First of all, thank you for this loader, it's a great idea!

I want to load several SVG icons using this loaded, but it always removes the <style> Element of the SVG, which is not what I want. I need the <style> Element to stay in place as it contains icon-specific options. I tried to disable the corresponding SVGO plugin using

```
            query: {
              svgo: {
                plugins: [
                  { removeStyleElement: false },
                ]
              }
            }
```

But this has no effect. Digging deeper, I noticed that `removeStyleElement` is a core plugin:

```
var essentialPlugins = ["removeDoctype", "removeComments", "removeStyleElement"];
```

It seems that I have no possibility to disable this plugin, is that correct? In this case, I could no longer use this project, which is quite sad. Is there really no option to disable removing the <style> element?

**Comment by boopathi** [comment]
`style` tag in SVG is not valid JSX. For babel to parse the svg as JSX it needs to be removed.

**Comment by hapulb** [comment]
if you are using adobe illustrator, you can change the svg styling format to "inline-css" via change the Asset Export panel's setting. And in sketch and Affinity Designer, it's a default option of using "inline-css"
![screen shot 2018-01-06 at 5 49 25 pm](https://user-images.githubusercontent.com/28030655/34638611-fdddfe62-f309-11e7-8295-1c19ed979f14.png)

**Comment by butchler** [comment]
If the SVGO version this loader uses is updated (see https://github.com/boopathi/react-svg-loader/issues/192), then you could use the new `inlineStyles` SVGO plugin (https://github.com/svg/svgo/blob/master/plugins/inlineStyles.js) to automatically convert everything in `<style>` to inline attributes on the individual paths/etc. (essentially the same approach as saving the SVG with inline CSS in your editor, but done via the plugin for you automatically).

**Comment by boopathi** [comment]
@butchler nice find. do you want to send a PR?

**Comment by butchler** [comment]
@boopathi I'm using https://github.com/smooth-code/svgr now, which uses a more recent version of SVGO. Sorry :(
