### ISSUE TITLE
Running minified production build fails for react-create-app

### ISSUE THREAD

**Issue by keaksey-sum** [boopathi/react-svg-loader#213]
Failed to minify the bundle. Error: static/js/0.2870ad60.chunk.js from UglifyJs

example of  import
export { default as bnsSetting } from '-!react-svg-loader!./next-settings.svg'

**Comment by atomanyih** [comment]
This might be the same issue:
building for production, we get this super helpful error from `create-react-app`:
```
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/react-svg-loader/lib/loader.js!./src/images/my-icon.svg:6
```

we got `create-react-app` to stop hiding errors and found this message:

```
{ errors:
   { errors:
      [ '\u001b[7mstatic/js/main.78aa09a2.js from UglifyJs\u001b[27m\nUnexpected token: operator (>) [./node_modules/react-svg-loader/lib/loader.js!./src/images/my-icon.svg:6,0][static/js/main.78aa09a2.js:42613,65]' ],
     warnings: [] } }
```

we disabled uglification to see what it was trying to uglify and saw this:

```
/* harmony default export */ __webpack_exports__["a"] = ((_ref) => {
```

so it seems like `react-svg-loader` isn't compiling down to es2015?

to fix it we manually added babel loader to the `svg` test in our webpack config:

```
      {
            test: [/\.svg$/],
            use: [
              {
                loader: "babel-loader"
              },
              {
                loader: require.resolve('react-svg-loader'),
              }
            ]
          },
```

I'm kind of surprised this wasn't happening by default

**Comment by alexeychikk** [comment]
I have very strange issue. Similar error is shown when build is running in docker container. When I locally run "yarn build" (ejected create-react-app config) then everything is ok, build successful. I've tried to add babel-loader as shown above and now I got the error locally.
@atomanyih Could you please tell how you configured to stop hiding errors?

**Comment by rlesniak** [comment]
Switching to https://github.com/jhamlet/svg-react-loader solves all problems
