### ISSUE TITLE
Identifier 'React' has already been declared

### ISSUE THREAD

**Issue by catamphetamine** [boopathi/react-svg-loader#216]
Seems that this babel plugin adds `import React from 'react'` for every `.js` file.

```
ERROR in ./src/routes.js
Module parse failed: Identifier 'React' has already been declared (8:7)
You may need an appropriate loader to handle this file type.
|
| import React from 'react';
| import React from 'react';
| import { Route, IndexRoute } from 'react-router';
```

Could be related to https://github.com/kesne/babel-plugin-inline-react-svg/issues/31

**Comment by PaulVDT** [comment]
Seem to be having the same problem after I added the inline-react-svg plugin

`[ error ] ./pages/index.tsx 3:7
Module parse failed: Identifier 'React' has already been declared (3:7)
You may need an appropriate loader to handle this file type.
| import _slicedToArray from "@babel/runtime-corejs2/helpers/esm/slicedToArray";
| import React from "react";
> import React from "react";
| import { useState } from 'react';`

**Comment by borisdiakur** [comment]
I’m also having this issue. Can we reopen this ticket?
