### ISSUE TITLE
SVGO plugins except removeTitle don't seem to work

### ISSUE THREAD

**Issue by uptickr** [boopathi/react-svg-loader#223]
How are the SVGO options passed?

I've tried the following two approaches, but both don't seem to work for any property other than removeTitle:

`
{
  loader: 'react-svg-loader',
    options: {
      jsx: true,
      svgo: {
      plugins: [{ removeTitle: true, removeDesc: true }],
      floatPrecision: 2,
      },
    },
}
`

and 

`
{
  loader: 'react-svg-loader',
    options: {
      jsx: true,
      svgo: {
      plugins: [{ removeTitle: true }, { removeDesc: true }],
      floatPrecision: 2,
      },
    },
}
`

**Comment by shakiba** [comment]
I have same problem, passing options to svgo doesn't work!
