### ISSUE TITLE
require.resolve for 'babel-preset-react'

### ISSUE THREAD

**Issue by qq286735628** [boopathi/react-svg-loader#233]
https://github.com/boopathi/react-svg-loader/blob/d3623e97a65214a626a7fb7f7b72f368f387388f/packages/react-svg-core/src/index.js#L24

current `babel-preset-react` is not `require.resolve`

try this

```
presets: jsx ? [] : [require.resolve('babel-preset-react')],
```

**Comment by boopathi** [comment]
why is this required? is it causing a bug for you?

**Comment by qq286735628** [comment]
like this:

https://github.com/boopathi/react-svg-loader/blob/master/packages/react-svg-core/src/index.js#L25

when `react-svg-loader` is a __devDependencies__ , `require.resolve` can help to find module correct

**Comment by qq286735628** [comment]
now presets should be because babel upgrade

`presets: jsx ? [] : [require.resolve('@babel/preset-react')],`
