### ISSUE TITLE
Warning: React does not recognize the `whiteSpace` prop on a DOM element. 

### ISSUE THREAD

**Issue by davidc360** [boopathi/react-svg-loader#240]
I'm getting a warning for all my SVG files: 
 Warning: React does not recognize the `whiteSpace` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `whitespace` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in path (at hunter.svg:10)
    in g (at hunter.svg:10)
    in svg (at hunter.svg:10)

hunter.svg: https://pastebin.com/z4a76Qxi
I don't find a 'whiteSpace' props in the file. 

Help would be much appreciated.

**Comment by boopathi** [comment]
the pastebin you linked to is removed.
