### ISSUE TITLE
Compatibility with Preact

### ISSUE THREAD

**Issue by alex996** [boopathi/react-svg-loader#251]
Any chance to make this package compatible with Preact? Specially, I'm asking about `rollup-plugin-react-svg`, but this could also extend to `babel-plugin-react-svg`.

Currently, the plugin tries to resolve `react`, which is hard-coded. Perhaps, it could expose an option to configure `preact` and its `h` pragma instead?

Thanks!

**Comment by jakub-g** [comment]
@alex996 see https://github.com/boopathi/react-svg-loader/issues/290
