### ISSUE TITLE
Publish 3.0.0 release

### ISSUE THREAD

**Issue by bcovdkelly** [boopathi/react-svg-loader#252]
Are there any plans to publish the latest 3.0.0 changes? It looks like there was a 3.0.0 commit in the project history, but I don't see a tag

**Comment by mhsalves** [comment]
I'm using the current version () and started vulnerability.
When will be published ?

![image](https://user-images.githubusercontent.com/30807170/54793042-072f2600-4c17-11e9-835c-bdaeb3c6051a.png)

**Comment by kieran** [comment]
would also love to see a build published!

**Comment by anderslindsgard** [comment]
Would love to see a v2.1.1 security related release. (js-yaml).

**Comment by pumanitro** [comment]
svgo version update is the most important in here. Would love to see it working.

**Comment by boopathi** [comment]
Published.
