### ISSUE TITLE
CHANGELOG for version 3.0.0

### ISSUE THREAD

**Issue by peterbe** [boopathi/react-svg-loader#257]
`npm outdated` is telling me there's a fancy new react-svg-loader 3.0.0. (At the time, it was released some [13 hours ago](https://www.npmjs.com/package/react-svg-loader))

But no [CHANGELOG](https://github.com/boopathi/react-svg-loader/blob/master/CHANGELOG.md) :(

**Comment by boopathi** [comment]
added changelog - https://github.com/boopathi/react-svg-loader/blob/master/CHANGELOG.md#300
