### ISSUE TITLE
Please don't remove viewbox via SVGO

### ISSUE THREAD

**Issue by redaxmedia** [boopathi/react-svg-loader#261]
Hello,

updating to 3.0.0 breaks each SVG used in my application as viewbox has been removed by SVGO.

Therefore I suggest to use the following as default:

```js
loader: 'react-svg-loader',
options: {
    svgo: {
        plugins: [
            {
                removeViewBox: false
            }
        ]
    }
}
```

It would be awesome to add some documentation how to adjust options inside README.md...

**Comment by kylemh** [comment]
[It is documented](https://github.com/boopathi/react-svg-loader/tree/master/packages/react-svg-loader#svgo-options), but I agree the default should be false, and this issue should be centered on that.

**Comment by redaxmedia** [comment]
Fine, I can test 3.0.2 once you released it.

**Comment by kylemh** [comment]
@redaxmedia I'm not a maintainer, just wanted to comment to help filter stuff. I'm sure they'll get to it ASAP 💪

**Comment by alxmiron** [comment]
In v3.0.3 viewboxes are also removed for me (except the case, when `width` and `height` are absent on `<svg>`)
