### ISSUE TITLE
How to forward refs?

### ISSUE THREAD

**Issue by chrispcode** [boopathi/react-svg-loader#262]
Alright, so I have been trying to use and imported SVG with react-pose. React-pose has nothing to do with the problem. A simple example would be:

```ts

import ExpandSVG from './assets/expand.svg';

const ExpandIcon = React.forwardRef((props, ref) => (
  <ExpandSVG ref={ref} />
));

function Example() {
  const refExpandIcon = useRef(null);

  function handleClick() {
    console.log(refExpandIcon);
  }

  return (
    <div>
      <button
        type="button"
        onClick={handleClick}
      >
        Log ref of the Icon Below
      </button>
      <ExpandIcon ref={refExpandIcon} />
    </div>
  );
}

```

So when I click the button I would expect that the refExpandIcon would be anything but null.
But instead I get a null;

![image](https://user-images.githubusercontent.com/7029482/57885798-0b994900-782c-11e9-903b-c4d273ddf535.png)

Also I get the following error:

![image](https://user-images.githubusercontent.com/7029482/57885871-3d121480-782c-11e9-89b4-0b507b7130d7.png)

Removing the `forwardRef` does not make a difference.

Any ideas? I feel like it is a super simple fix

**Comment by Finesse** [comment]
The author of this library must forward the ref, not you.

You can try this workaround:

```jsx
function Example() {
  const expandIconWrapRef = useRef();

  function handleClick() {
    console.log(expandIconWrapRef.current.querySelector('svg'));
  }

  return (
    <div>
      <button
        type="button"
        onClick={handleClick}
      >
        Log ref of the Icon Below
      </button>
      <span ref={expandIconWrapRef}>
        <ExpandIcon />
      </span>
    </div>
  );
}
```

**Comment by chrispcode** [comment]
I see, but isn't a good idea to integrate this in the library as well?

**Comment by Finesse** [comment]
I think it's a good idea. I wrote it in my message:

> The author of this library must forward the ref, not you.

**Comment by tristanMatthias** [comment]
Can we please put this in 🙏? Happy to write a PR if needed
