### ISSUE TITLE
Passing className to SVG replaces already present classes

### ISSUE THREAD

**Issue by SpadarShut** [boopathi/react-svg-loader#27]
First, thank you for fixing the reported bugs! 
I've found another issue related to classes. So I've built some SVG components using command line and `addClassesToSvgElement` svgo plugin, and it worked good, adding `Icon` className to the root SVG. But now when I use this component and add another class to it like `<MyPreBuiltSVGIcon className="extraClass"/>`, the `extraClass` replaces the original `Icon` class, but instead it should be added.

**Comment by boopathi** [comment]
Hmm... Interesting. This would be a new feature. Simply appending won't suffice and will be buggy. Using something like classnames is one option, but will force the users to include classnames in their package.

If you've any ideas already, feel free to send a PR.

**Comment by SpadarShut** [comment]
I think splitting class string by whitespace and merging the array back with the new classes would be enough for a fix.

**Comment by SpadarShut** [comment]
I could try to implement this, but I am not sure where is the best place to put this code.

**Comment by boopathi** [comment]
should go somewhere here. 😃 

https://github.com/boopathi/react-svg-loader/blob/25a166c8411be42a3e99a44e8c7aa6e7396d7637/src/plugin.js#L23

**Comment by SpadarShut** [comment]
Can you explain how root attributes get turned into `this.props.className ? this.props.className : "Icon"` ?

**Comment by boopathi** [comment]
In master, now it doesn't.

```
<svg width="50">
``` 

is converted to

```
<svg width="50" {...this.props}/>
```

So, if `this.props` has width attr, it overwrites the existing one.
