### ISSUE TITLE
SVGO options applied incorrectly

### ISSUE THREAD

**Issue by Mindtraveller** [boopathi/react-svg-loader#276]
Here is a configuration:

```
{
  loader: 'react-svg-loader',
  options: {
    jsx: true,
    svgo: {
      plugins: [
        {
          convertShapeToPath: false,
          removeTitle: true,
          removeDesc: true,
        },
      ],
    },
  },
```
All SVGO options work fine there.

But once new **false** option is added, next **false** options after it stop working. **true** options seems to still work fine.

```
{
  removeViewBox: false,
  convertShapeToPath: false,
  removeTitle: true,
  removeDesc: true,
}
```
In the example above `convertShapeToPath` stops working after adding `removeViewBox` though it worked fine before. If the `convertShapeToPath` goes first - `removeViewBox` does not work then.

**Comment by Mindtraveller** [comment]
is this repo still alive?

**Comment by moklick** [comment]
Hey @Mindtraveller 

I think it's:

```javascript
{
  loader: 'react-svg-loader',
  options: {
    jsx: true,
    svgo: {
      plugins: [
         { convertShapeToPath: false },
         { removeTitle: true },
         { removeDesc: true }
      ],
    },
  },
```

**Comment by Mindtraveller** [comment]
@moklick shame on me...
thanks, that now works
