### ISSUE TITLE
parse fails when parsing style tag

### ISSUE THREAD

**Issue by atomanyih** [boopathi/react-svg-loader#38]
We've got an svg that looks kind of like this:

``` svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <style>
      .clipped-thing {
        clip-path: url(#clip-path);
      }  
    </style>
    <clipPath id="clip-path">
      <rect y="-0.86" width="375" height="177"/>
    </clipPath>
  </defs>
  <g class="clipped-thing">
    <!-- SOME SVG STUFF -->
  </g>
</svg>
```

loading this svg fails with: `Module build failed: SyntaxError: unknown: Unexpected token` on `clip-path: url(#clip-path);`

**Comment by boopathi** [comment]
Ah! Do SVGs normally have a style tag?

The loader does not parse style tags now. For a workaround, move it to outside the svg file. I'll find some time to add this. Also, PR welcome! 😃

**Comment by atomanyih** [comment]
Yeah it does: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/style

pretty weird but sometimes we get svgs like this.

it's not an immediate issue for us; our designer exported it differently
and it came out nicer. just thought you might like to know!

**Comment by seleckis** [comment]
I need this very much. may be it is possible to optimize file with svgo first, than react-svg? For now, I guess, svg file is parsed with react-svg-loader first and then runs svgo, isn't it?

**Comment by boopathi** [comment]
@seleckis This is the pipeline - https://github.com/boopathi/react-svg-loader#internals , It runs svgo first and then transformations are applied.

There is a limitation. This is not easy to implement because, using a HTML parser (I tried with parse5), you can't use arbitrary strings in the style tag - basically, do this - 

transform 

```html
<style>
.red { color: red }
</style>
```

to

```jsx
<style>
{` .red { color: red } `}
</style>
```

which is jsx and will be understood by the jsx parser. If you know of any html parser that lets you do this, just post it here, I can try it out and add it.

**Comment by seleckis** [comment]
In this case, why  plugins: [{ removeStyleElement: true }], does not work?

**Comment by seleckis** [comment]
Why webpack shows me an error where I see not optimized SVG?
```
ERROR in ./~/babel-loader!./~/react-svg-loader/lib/loader.js!./src/assets/svg/expand.svg
Module build failed: SyntaxError: unknown: Unexpected token (1:112)
> 1 | <svg id="Ebene_2" xmlns="http://www.w3.org/2000/svg" width="24" height="16" viewBox="0 0 24 16"><style>.st0{fill:#fff}</style><path d="M0 0v16h24V0H0zm22 14h-6V2h6v12z"/><path class="st0" d="M6.2 6
.8L9 4l1.2 1.2L7.4 8l2.8 2.8L9 12 5 8z"/></svg>
```
it tries to parse before svgo

**Comment by boopathi** [comment]
It seems to work for me - https://github.com/boopathi/react-svg-loader/commit/1bb152ef6871511198d8f221271a9783449729c6#diff-9bb3de20ef60fb0751fb0025b2cd27eaR22 . It removes the style tags from the svgs.

**Comment by seleckis** [comment]
If I write same url as you have I get an error:
```
Module not found: Error: Cannot resolve 'file' or 'directory'
```

I found the solution to define loaders in an url like this:
```
import icon from '-!babel!react-svg!../assets/svg/icon.svg';
```
now it loads the file, but svgo does not work properly.

**Comment by boopathi** [comment]
@seleckis SVGO options are passed to react-svg-loader. 

+ Passing parameters to loaders - https://webpack.github.io/docs/loaders.html#parameters
+ What SVGO options does react-svg-loader take and how can you pass it? - https://github.com/boopathi/react-svg-loader#svgo-options

**Comment by seleckis** [comment]
Oh, sorry, I used webpack 2 config instead of webpack 1.x. But anyway, my config:
```
test: /\.svg$/,
  loader: 'babel!react-svg?' + JSON.stringify({
    svgo: {
      // svgo options
      plugins: [{removeStyleElement: false}],
      floatPrecision: 2
    }
  }),
},
```
and when I import svg like: 
```
import icon from '../assets/svg/icon.svg';
```
I get an error:
```
Module build failed: SyntaxError: unknown: Unexpected token (1:112)
> 1 | <svg id="Ebene_2" xmlns="http://www.w3.org/2000/svg" width="24" height="16" viewBox="0 0 24 16"><style>.st0{fill:#fff}</style><path d="M0 0v16h24V0H0zm22 14h-6V2h6v12z"/><path class="st0" d="M6.2 6
.8L9 4l1.2 1.2L7.4 8l2.8 2.8L9 12 5 8z"/></svg>
```
where style tag still persists.

**Comment by seleckis** [comment]
Oh, sorry, I have used webpack 2.x config instead of webpack 1.x. Now everything works properly. So for this issue I suggest to use svgo config  with removeStyleElement: true
