### ISSUE TITLE
[q] When you try to test on a different env (not webpack) how you skip svg imports

### ISSUE THREAD

**Issue by alexrqs** [boopathi/react-svg-loader#48]
#### Scenario
React component working with webpack very regular mstuff but when you try to test without webpack on the equation.
```
Error: Cannot find module '-!babel!svg-react!./../../assets/waitspinner.svg'
```
any work around ?
or any official way to skip this or a nice way to include this on the tests?

**Comment by boopathi** [comment]
You should not use require("<loader>!./image.svg") then. You should use the loader config in webpack.config.js. Now with [node require.extensions](https://nodejs.org/api/globals.html#globals_require_extensions) (which is a deprecated feature), you can handle how svgs are handled. Or as suggested in the node docs, you can do compilation to replace/remove these requires in a build step before you run the code. You can write a babel plugin that does this. Or if you're determinant of how you'll use the require statements, you can as well write a `regex` to remove these requires/replace them with something that will make sense in your code.

OR another option would be (I would suggest this) - 

To use react-svg-loader without webpack, you can use the CLI and transform you `image.svg` to `image.svg.react.js` and use `require('./image.svg.react')` and it will simply work, cuz the SVG is now transform to a React Component and is just JavaScript.
