### ISSUE TITLE
 "ReferenceError: React is not defined" with server side rendering

### ISSUE THREAD

**Issue by tconroy** [boopathi/react-svg-loader#55]
EDIT: how silly of me -- I seem to have mixed up `react-svg-loader` and `svg-react-loader`, the later of which my issue is with.

Apologies! Please feel free to close this.

**Comment by tconroy** [comment]
@boopathi this is the content of `circle.inline.svg`... It was working fine when I was running a local `webpack-dev-server` (no express backend just developing locally), without any import statement.

```
<svg
  version="1.1"
  xmlns="http://www.w3.org/2000/svg"
  x="0px"
  y="0px"
  viewBox="0 0 100 100"
  enable-background="new 0 0 100 100"
>
  <circle
    className="svg-inline-circle"
    cx="50"
    cy="50"
    r="48"
  >
  </circle>
</svg>
```

**Comment by boopathi** [comment]
Ah. Cool!.
