### ISSUE TITLE
Unable to set fill with props

### ISSUE THREAD

**Issue by piotrblasiak** [boopathi/react-svg-loader#9]
Docs say: <Image width={400} height={200} fill='#abcdef' />
But I can´t figure out how to make that work?

**Comment by boopathi** [comment]
The props will be applied to the `<svg /> element, and I can see it's getting applied (`fill` in this case).

<img width="651" alt="screenshot 2016-03-04 17 01 02" src="https://cloud.githubusercontent.com/assets/294474/13532264/cd235ed0-e22a-11e5-912f-4ac6d15a16e2.png">

Do you have the code where it fails ? Could be a bug somewhere, will try to fix it up.

**Comment by piotrblasiak** [comment]
Ok maybe I don´t have a clear enough understanding of SVG but I can´t see how a fill property on the svg element could change the fill color of the svg shape? You need to use css or set fill on specific paths?

**Comment by boopathi** [comment]
Yes. Hand editing the svg may be a better idea. Directly change the fill for the path you'd want.

**Comment by piotrblasiak** [comment]
Yeah that´s what I ended up doing. Will still use this for static svg:s tho. You might want to remove the fill=... example from the docs to avoid confusion ;)

**Comment by boopathi** [comment]
Yeah. Cool. Better without fill attr.

If this is resolved, would you mind closing the issue ?

**Comment by piotrblasiak** [comment]
Sure, thanks for the quick reply!

**Comment by Pczek** [comment]
However, it would be a very handy feature to change the fill color of all children. I'm in need of this, because my Icons should be a plain color and multicoloured on hover.

```
<Icon fill={hover ? null : #ffffff} />
```
